name: libirmin

on:
  push:
    branches:
      - master

jobs:
  python:
    strategy:
      fail-fast: true
      matrix:
        os:
          #- macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.13.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler}}

      - run: "opam pin add repr.dev --dev-repo"
      - run: "opam pin add ppx_repr.dev --dev-repo"
      - run: "opam pin add index.dev --dev-repo"
      - run: "opam pin add irmin.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add ppx_irmin.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add irmin-fs.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add irmin-git.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add irmin-pack.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add irmin-http.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add irmin-graphql.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add irmin-tezos.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add irmin-unix.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam pin add libirmin.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: opam install libirmin
      - run: find . -name libirmin.so
      - run: pip3 install cffi pytest --user
      - run: opam exec -- pip3 install . --user
      - run: opam exec -- pydoc -w irmin.irmin
      - run: mkdir -p doc
      - run: mv irmin.irmin.html doc/index.html
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./doc
          force_orphan: true

