name: libirmin

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  python:
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.13.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler}}

      - run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install ca-certificates
          fi
      - run: "opam pin add libirmin.dev git+https://github.com/zshipko/libirmin.git --no-action"
      - run: opam install libirmin
      - run: find . -name libirmin.so
      - run: pip3 install cffi pytest --user
      - run: opam exec -- pip3 install . --user
      - run: opam exec -- py.test test.py

